# Site settings
title: SKIES Mobile
description: A modern iOS application for team connectivity and content sharing
baseurl: ""
url: "https://skies.vakesz.com"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Include the _pages directory
include:
  - _pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/

# Just the Docs theme settings
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/vakesz/Skies-iOS"

# Footer content
footer_content: "© 2025 SKIES Mobile."

# Color scheme
color_scheme: nil

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
